PRINT 'Start adding default Evaluation Questions'

INSERT INTO EvaluationFormQuestions (EvaluationFormQuestionType, RowSequence, IsActive, DateAdded, [Text])
VALUES
(1, 1, 1, GETUTCDATE(), 'Have any exceptions been requested on this application? If yes, attach exception approvals and explanation to STG.'),
(1, 2, 1, GETUTCDATE(), 'Are costs of training competitively priced with similar courses offered in the sector (and if a private trainer, by PTIB- certified organizations in BC)?'),
(1, 3, 1, GETUTCDATE(), 'Is applicant eligible <a href="https://www.workbc.ca/getmedia/7ee83806-6cb8-413b-9179-6cc6863f0c26/Eligibility-Criteria-CWRG.pdf.aspx" target="_blank">for chosen stream</a>?'),
(1, 4, 1, GETUTCDATE(), 'Is the applicant in good standing on <a href="https://www.bconline.gov.bc.ca/" target="_blank">BC Online</a>?'),
(1, 5, 1, GETUTCDATE(), 'Does the skills trainer meet the <a href="https://www.workbc.ca/getmedia/7ee83806-6cb8-413b-9179-6cc6863f0c26/Eligibility-Criteria-CWRG.pdf.aspx" target="_blank">eligibility criteria</a>?'),
(1, 6, 1, GETUTCDATE(), 'Is the skills trainer flagged?'),
(1, 7, 1, GETUTCDATE(), 'If yes, does this affect eligibility?'),
(1, 8, 1, GETUTCDATE(), 'Any flags on the applicant?'),
(1, 9, 1, GETUTCDATE(), 'If yes, does this affect eligibility?'),
(1, 10, 1, GETUTCDATE(), 'Does this application meet the intention of the stream and demonstrate and immediate skills training need in a community facing labour market challenges or opportunities (supported by description, letters, etc.)?'),
(1, 11, 1, GETUTCDATE(), 'Will the entire project (recruitment, training, wraparound supports) be completed within 52 weeks?'),
(1, 12, 1, GETUTCDATE(), 'For Indigenous Communities only: Does the proposed project support urban or rural Indigenous communities located in BC? (On or off reserve)?'),
(1, 13, 1, GETUTCDATE(), 'For Community Response only: Is the community directly impacted (<a href="https://www2.gov.bc.ca/assets/gov/farming-natural-resources-and-industry/forestry/stewardship/old-growth-forests/old_growth_pt13.png" target="_blank">See map</a>) and has this been confirmed by the Ministry of Jobs, Economic Recovery and Innovation) and/or MoF (Ministry of Forests)?'),
(1, 14, 1, GETUTCDATE(), 'Has the physical location of training been confirmed? Ensure confirmed address is reflected in system and any changes must be communicated to AO 18.'),
(1, 15, 1, GETUTCDATE(), 'Is Applicant engaging a private post-secondary institution (either <a href="https://www.privatetraininginstitutions.gov.bc.ca/students/pti-directory" target="_blank">PTIB-certified</a> or non-PTIB-certified) OR a Continuing Education department of a PPSI as the training provider?'),
(1, 16, 1, GETUTCDATE(), 'If yes: Are the course outline and instructor qualifications attached?'),
(1, 17, 1, GETUTCDATE(), 'Is the course <a href="https://skilledtradesbc.ca/" target="_blank">STBC Designated</a> or <a href="https://www.privatetraininginstitutions.gov.bc.ca/students/pti-directory" target="_blank">PTIB approved</a> and if PTIB approved have you confirmed all courses match the <a href="\\SFP.IDIR.BCGOV\S124\S24026\CWRG\Admin\Admin, Gen-100\P & P-00\Templates\Evaluation" target="_blank">PTIB provided spreadsheet</a>?'),
(1, 18, 1, GETUTCDATE(), 'If the PTIB Designated institution is offering a customized course that is NOT on the PTIB website, has the customized course been submitted to PTIB for approval?'),
(1, 19, 1, GETUTCDATE(), 'Is the training for occupational skills training or for an Apprenticeship Foundation program? Note: only Foundation programs are eligible.'),
(1, 20, 1, GETUTCDATE(), 'Has the curriculum been reviewed to ensure it is predominantly occupational skills? (90% +). Note: Short Term Occupational Certifications (STOCs) cannot make up majority of training.'),
(1, 21, 1, GETUTCDATE(), 'Will the certification graduates receive be employer-recognized or regulated by a governing body?'),
(1, 22, 1, GETUTCDATE(), 'For <a href="https://www.cdsbc.org/registration-renewal/certified-dental-assistants/cda-certification-requirements-and-forms/cda-schools-bc" target="_blank">Dental Assistant</a>, <a href="https://www.makeafuture.ca/careers-in-bc-education/support-staff/education-assistants/" target="_blank">Early Childhood Education</a> and <a href="https://www.bcsls.net/certification#MLAcert" target="_blank">Medical Lab Assistant</a> training, have you confirmed trainer is accredited?'),
(1, 23, 1, GETUTCDATE(), 'Do all services delivered fall within the list of Eligible Services in the criteria? Note: Essential services are no longer eligible under Skills Training unless part of PTIB-approved curriculum.'),
(1, 24, 1, GETUTCDATE(), 'Does curriculum include ESS component? Note: if yes, additional ESS funds are not eligible.'),
(1, 25, 1, GETUTCDATE(), 'Does the project request additional funds for Employment Support Services (ESS)?'),
(1, 26, 1, GETUTCDATE(), 'Is the Employment Support Services (ESS) provider 3rd party to the applicant?'),
(1, 27, 1, GETUTCDATE(), 'Does the ESS provider meet eligibility criteria?'),
(1, 28, 1, GETUTCDATE(), 'Is ESS being delivered as a cohort?'),
(1, 29, 1, GETUTCDATE(), 'Have ESS outline and instructor qualifications been submitted and reviewed?'),
(1, 30, 1, GETUTCDATE(), 'Are the services provided under ESS included in the training dates? Note: this is a requirement. If training dates are edited, inform AO 18.'),
(1, 31, 1, GETUTCDATE(), 'Are all proposed services for ESS eligible as per the eligibility criteria? Note: max $400 per participant and Essential Skills cannot be a standalone component of ESS.'),
(1, 32, 1, GETUTCDATE(), 'Has a quote been received from ESS provider?'),
(1, 33, 1, GETUTCDATE(), 'Are all proposed participant financial supports including ‘Other Supports’ eligible per Table 1 of the Eligibility Criteria?'),
(1, 34, 1, GETUTCDATE(), 'Is the total budget below $300,000.00?'),
(1, 35, 1, GETUTCDATE(), 'For Emerging Priorities, Indigenous Communities, Workforce Shortages: Does application exceed the $15,000 maximum cost per participant? ($10K ST and $5K in Supports/ ESS maxed at $400 per participant).'),
(1, 36, 1, GETUTCDATE(), 'For Community Response only: Does the application exceed the maximum of $20,000 per participant? ($10K ST, $5K supports, $400 max ESS, $5K max allowance).'),
(1, 37, 1, GETUTCDATE(), 'For Emerging Priorities, Workforce Shortages and Community Response: Are administration costs equal or less than 10%?'),
(1, 38, 1, GETUTCDATE(), 'For Indigenous Communities only: Are administration costs equal or less than 10%? If Indigenous Cultural supports are included, are administration costs equal or less than 12% of total project costs?'),
(1, 39, 1, GETUTCDATE(), 'Has quote from skills training provider been received? Do costs align with STG?'),
(1, 40, 1, GETUTCDATE(), 'Has applicant received previous funding from CWRG?'),
(1, 41, 1, GETUTCDATE(), 'If yes, are all obligations up to date?'),
(1, 42, 1, GETUTCDATE(), 'Has this applicant been funded for this project previously and do previous outcomes suggest this project was successful?'),
(1, 43, 1, GETUTCDATE(), 'Is insurance company listed with <a href="https://www.bcfsa.ca/public-resources/insurance/authorized-insurance-companies" target="_blank">BCFSA</a>? Note: if insurance provider cannot be located, email <a href="mailto:ProcurementSupport@gov.bc.ca" target="_blank">ProcurementSupport@gov.bc.ca</a> to confirm. No application can be approved without valid insurance.'),
(1, 44, 1, GETUTCDATE(), 'If no, is the insurer on the list of <a href="\\sfp.idir.bcgov\s124\S24026\CWRG\Admin\Admin, Gen-100\Gen-01\RMB Reviewed Insurers.docx" target="_blank">RMB reviewed insurers</a>?'),
(1, 45, 1, GETUTCDATE(), 'If no, is the organization covered by <a href="https://curie.org/risk-management/" target="_blank">CURIE</a> or <a href="https://www.bcucipp.org/?q=Memorandum_of_Coverage" target="_blank">UCIPP</a>?'),
(1, 46, 1, GETUTCDATE(), 'Does the insurance cover a minimum of $2 million in General Commercial Liability?'),
(1, 47, 1, GETUTCDATE(), 'Does the insurance expire during the project?'),
(2, 48, 1, GETUTCDATE(), 'Is this project for employment or self-employment?'),
(0, 49, 1, GETUTCDATE(), 'For employment:'),
(1, 50, 1, GETUTCDATE(), 'Are there letters of support from employers willing to interview graduates for potential employment? If interviews are not offered, do the letters indicate the need and support the training?'),
(1, 51, 1, GETUTCDATE(), 'Do the letters of support show that employers are familiar with the curriculum and knowledgeable about the certification or credential graduates will receive?'),
(1, 52, 1, GETUTCDATE(), 'Do the letters meet our criteria (not templated, dated, on official letterhead, etc.)?'),
(0, 53, 1, GETUTCDATE(), 'For self-employment:'),
(1, 54, 1, GETUTCDATE(), 'Did the applicant contact CWRG to discuss this self-employment project before submitting?'),
(1, 55, 1, GETUTCDATE(), 'Applications for self-employment training must clearly indicate the need for such training in the community and specify the goal of self-employment. Does the application indicate this?'),
(1, 56, 1, GETUTCDATE(), 'Does the application give a description of need and opportunity for this type of self-employment in the community?'),
(1, 57, 1, GETUTCDATE(), 'Projects for self-employment training must demonstrate that the products or services created by project participants are customer focussed and demand driven.  Does the training focus on this as either a screening pre-requisite (i.e., participants have a business idea in mind before joining training), or an objective of training?')

PRINT 'End adding default Evaluation Questions'
